name: Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.IP }}
          username: karan
          key: ${{ secrets.PROJECT }}
          script: |
            cd /home/karan/

            git clone https://github.com/KaranManhas22/seedlyfrntd.git
            cd /home/karan/seedlyfrntd
            npm install

            npm i pm2 -g

            npm run build || true

            pm2 restart app || pm2 start npm --name "app" -- run dev
